// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/proto/health.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_api_proto_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_health_proto_rawDescGZIP(), []int{0}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsActive      bool                   `protobuf:"varint,1,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	UptimeSeconds int32                  `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	ActiveUsers   int32                  `protobuf:"varint,3,opt,name=active_users,json=activeUsers,proto3" json:"active_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_api_proto_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_health_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *StatusResponse) GetUptimeSeconds() int32 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *StatusResponse) GetActiveUsers() int32 {
	if x != nil {
		return x.ActiveUsers
	}
	return 0
}

var File_api_proto_health_proto protoreflect.FileDescriptor

const file_api_proto_health_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/health.proto\x12\x14com.xealgo.muddy.api\"\x0f\n" +
	"\rStatusRequest\"w\n" +
	"\x0eStatusResponse\x12\x1b\n" +
	"\tis_active\x18\x01 \x01(\bR\bisActive\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x05R\ruptimeSeconds\x12!\n" +
	"\factive_users\x18\x03 \x01(\x05R\vactiveUsers2g\n" +
	"\rHealthService\x12V\n" +
	"\tGetStatus\x12#.com.xealgo.muddy.api.StatusRequest\x1a$.com.xealgo.muddy.api.StatusResponseB\bZ\x06./;apib\x06proto3"

var (
	file_api_proto_health_proto_rawDescOnce sync.Once
	file_api_proto_health_proto_rawDescData []byte
)

func file_api_proto_health_proto_rawDescGZIP() []byte {
	file_api_proto_health_proto_rawDescOnce.Do(func() {
		file_api_proto_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_health_proto_rawDesc), len(file_api_proto_health_proto_rawDesc)))
	})
	return file_api_proto_health_proto_rawDescData
}

var file_api_proto_health_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_health_proto_goTypes = []any{
	(*StatusRequest)(nil),  // 0: com.xealgo.muddy.api.StatusRequest
	(*StatusResponse)(nil), // 1: com.xealgo.muddy.api.StatusResponse
}
var file_api_proto_health_proto_depIdxs = []int32{
	0, // 0: com.xealgo.muddy.api.HealthService.GetStatus:input_type -> com.xealgo.muddy.api.StatusRequest
	1, // 1: com.xealgo.muddy.api.HealthService.GetStatus:output_type -> com.xealgo.muddy.api.StatusResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_health_proto_init() }
func file_api_proto_health_proto_init() {
	if File_api_proto_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_health_proto_rawDesc), len(file_api_proto_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_health_proto_goTypes,
		DependencyIndexes: file_api_proto_health_proto_depIdxs,
		MessageInfos:      file_api_proto_health_proto_msgTypes,
	}.Build()
	File_api_proto_health_proto = out.File
	file_api_proto_health_proto_goTypes = nil
	file_api_proto_health_proto_depIdxs = nil
}
